on: ["push", "pull_request"]
name: Test Coveralls
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
